# Default values for policy-as-code.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: pipy
replicaCount: 1
tag: "0.8.0-31"
port: 6443
gui:
  enabled: false
  port: 6060
logLevel: info 

scriptURL: "http://192.168.1.101:9999/rule/image.js"  